### PR TITLE
Darknet reads images as rgb

### PR DESCRIPTION
**Pull request by voibit**

### CODE REVIEW

**Comment by prabindh** [comment]
Thanks! But in load_image_cv(), bgr from cvLoadImage gets converted to rgb. Do you think this patch is still required ?

**Comment by prabindh** [comment]
I spoke too soon. If we were to match the load_image_cv behaviour, a conversion is needed. Let me see this again. What was the trigger for this patch ?

**Comment by voibit** [comment]
I trained a network with two different objects, namely red and green (ish). for a long time i could not figure out why arapaho showed wrong classifications though darknet-cpp got it right. Then i tested with a red image, and printed out what actually went to network_predict(),  in detector.c and arapaho.cpp. The first couple of floats for detector.c was 1, and  for arapaho.cpp they were 0, bingo. 

I have yet to deep deeper into the sourcecode of darknet. :sweat_smile:

**Comment by prabindh** [comment]
Interesting test for color. I will see later if there is an optimal way to include it in the scaling step itself. In the meantime, can you please: 
1) Remove the unnecessary newlines at 266 and 269 and resubmit ?

**Review by prabindh — APPROVED** [review]
Ack.

**Comment by prabindh** [comment]
Done. Thanks. Also raised an issue on your behalf - https://github.com/prabindh/darknet/issues/35.

**Pull request merged**
