### PR TITLE
Freeing VRAM and RAM in arapaho destructor

### PR DESCRIPTION
**Pull request by turkishviking**
Hi,

I had some problems with arapaho destructor not being able to free ram and vram.
I have modified arapaho.cpp to do that (near to TODO : massive cleanup ;) ).

It is not perfect, I can't figure how to cleanup network.input_gpu and network.truth_gpu, but you can create and remove arapaho objects without going out of memory (both vram and ram).

It works for me on linux 64bits, cuda8, cudnn 5.1, gtx980, gcc and g++ 5.4

### CODE REVIEW

**Review by prabindh — COMMENTED** [review]
Thanks. After freeing, it is a good practice to set the (freed) pointers to NULL. Can we add that please ?

**Comment by turkishviking** [comment]
Yes of course, tell me if it is sufficient

**Review by prabindh — APPROVED** [review]
Thanks.

**Comment by prabindh** [comment]
Can we run this in a loop - with a create/destroy sequence of the object, for an overnight run ?

**Comment by turkishviking** [comment]
Yes, I think it will be ok, I use that to switch yolo network on the fly. I haven't notice  leakage yet. But
like I said in the commit,  net.input_gpu and net.truth_gpu aren't freed, im interested of the result of an overnight run, you will do that?

**Comment by prabindh** [comment]
With the yolov3 mainline sync in the master branch, this patch needs some changes, can you please check ?

**Comment by turkishviking** [comment]
ok, this is done (not a big conflict ^^⁾

**Comment by prabindh** [comment]
this change fails build, because `net` is now a pointer, not a struct. Please check,

**Comment by turkishviking** [comment]
ho sorry, I didn't see that, i 'll check

**Comment by turkishviking** [comment]
OK, this is done, it'now much more easy with net as pointer :)

**Comment by prabindh** [comment]
There is no `boxes` field, as it is part of the `detection` structure.

**Comment by turkishviking** [comment]
Sorry , it remains from the Yolo-V2 version, I'm not on today

**Comment by prabindh** [comment]
Please also set `net` to NULL after free.

**Comment by turkishviking** [comment]
done

**Review by prabindh — APPROVED** [review]

**Pull request merged**
