### PR TITLE
Make sure we include openCV only if defined

### PR DESCRIPTION
**Pull request by pliablepixels**
fails compilation otherwise

### CODE REVIEW

**Comment by prabindh** [comment]
It is better to move the ifdef OPENCV conditional, outside the __cplusplus check, like below, as both cases are impacted:
ifdef OPENCV
    ifdef __cplusplus

**Comment by pliablepixels** [comment]
true. It also turns out other files like `test.cpp` also include opencv without `#ifdef`

Edit: actually, looks like test.cpp needs opencv. 

Would you consider authoring a simpler test or an alternate that simply runs darknet and prints out a detection string match, given an image?

**Comment by prabindh** [comment]
Test.cpp relies on CV for format conversions, and is only for Arapaho testing (that  uses darknet_cpp dll). The darknet_cpp executable binary  can always be run without openCV, with this proposed change. So I suggest we push this change without test.cpp.

**Comment by prabindh** [comment]
Ping, Would you be able to move the OpenCV check outside the conditionals ?

**Review by prabindh — APPROVED** [review]

**Comment by prabindh** [comment]
Merging

**Pull request merged**
